# Master playbook

- hosts: localhost
  tasks:
    - include_tasks: tasks_macos/core-setup.yml
      tags: 
        - core
    - include_tasks: tasks_macos/dotfiles.yml
      tags: 
        - dotfiles
    - include_tasks: tasks_macos/alacritty.yml
      tags: 
        - alacritty
    - include_tasks: tasks_macos/python-setup.yml
      tags: 
        - python
    - include_tasks: tasks_macos/robotics-setup.yml
      tags: 
        - robotics
