# Master playbook

- hosts: localhost
  tasks:
    - include_tasks: tasks_macos/core-setup.yml
      tags: 
        - core
    - include_tasks: tasks_macos/dotfiles.yml
      tags: 
        - dotfiles
