# Master playbook

- hosts: localhost
  tasks:
    - include_tasks: tasks_rhel/fzf.yml
      tags:
        - fzf
    - include_tasks: tasks_rhel/core-setup.yml
      tags:
        - core
    - include_tasks: tasks_rhel/dotfiles.yml
      tags:
        - dotfiles
    - include_tasks: tasks_rhel/node-setup.yml
      tags:
        - node
    - include_tasks: tasks_rhel/neovim-setup.yml
      tags:
        - neovim
    - include_tasks: tasks_rhel/tmux-setup.yml
      tags:
        - tmux
