# Master playbook

- hosts: localhost
  tasks:
    - include_tasks: tasks_ubuntu/dotfiles.yml
      tags:
        - dotfiles
    - include_tasks: tasks_ubuntu/fzf.yml
      tags:
        - fzf
    - include_tasks: tasks_ubuntu/core-setup.yml
      tags:
        - core
    - include_tasks: tasks_ubuntu/neovim-setup.yml
      tags:
        - neovim
    - include_tasks: tasks_ubuntu/lua-setup.yml
      tags:
        - lua
    - include_tasks: tasks_ubuntu/node-setup.yml
      tags:
        - node
    - include_tasks: tasks_ubuntu/tmux-setup.yml
      tags:
        - tmux
    - include_tasks: tasks_ubuntu/python-setup.yml
      tags:
        - python
    - include_tasks: tasks_ubuntu/ros2-setup.yml
      tags:
        - ros2
          #- include_tasks: tasks_ubuntu/julia-setup.yml
          #tags:
          #- julia
