- name: Clone fzf
  ansible.builtin.git:
    repo: 'https://github.com/junegunn/fzf.git'
    dest: "{{ lookup('env', 'HOME') }}/.fzf"
    recursive: no
    version: master
  tags:
    - install
    - fzf
- name: Install fzf
  shell: "~/.fzf/install"
