- name: Installing stow
  apt: name=stow
  tags:
    - install
    - dotfiles
    - stow
- name: Cloning dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:Benji19967/dotfiles.git'
    dest: "{{ lookup('env', 'WORKSPACE') }}/dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - install
    - dotfiles
    - stow
- name: Stow dotfiles
  shell: cd $WORKSPACE/dotfiles && ./install
  tags:
    - install
    - dotfiles
    - stow
